name: Deploy Streamlit App to Azure Web App

on:
  push:
    branches:
      - main  # or your default branch

env:
  AZURE_WEBAPP_NAME: movie-review-app     # 🔹 Replace with your Azure Web App name
  PYTHON_VERSION: '3.11'                  # 🔹 Azure supports 3.9–3.12
  AZURE_RESOURCE_GROUP: movie-review-rg   # Optional: your resource group name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: production

    steps:
    - name: Download artifact from build
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
